
CREATE TABLE DataVoipRecord (
    telco_id text,
    begin_connection_time timestamp with time zone,
    end_connection_time timestamp with time zone,
    client_info text,
    server_info text,
    point_id integer,
    voip_session_id text,
    voip_conference_id text,
    voip_duration integer,
    voip_originator_name text,
    voip_call_type_id integer,
    calling_original_number text,
    calling_translated_number text,
    calling_e164_number text,
    called_original_number text,
    called_translated_number text,
    called_e164_number text,
    voip_in_bytes_count bigint,
    voip_out_bytes_count bigint,
    voip_fax boolean,
    voip_term_cause text,
    inbound_trunk text,
    outbound_trunk text,
    voip_gateways text,
    voip_protocol text,
    supplement_service_id integer,
    voip_abonent_id text,
    voip_nat_info text,
    voip_location text,
    voip_event text,
    voip_data_content_id text,
    vpbx_id integer,
    server_id integer,
    account_id integer,
    account_id_2 integer
);
